# Generated by Django 5.1.1 on 2024-11-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0002_alter_tipopessoa_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('valor', models.FloatField()),
                ('valor_atual', models.FloatField(default=0)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primeiro_app.pessoa')),
            ],
        ),
    ]
