# Generated by Django 5.1.2 on 2024-11-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0002_alter_tipopessoa_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Fixa', 'Despesa Fixa'), ('Variavel', 'Despesa Variável'), ('Geral', 'Despesa Geral'), ('Investimento', 'Investimento'), ('Operacionais', 'Despesas operacionais'), ('Não Operacionais', 'Despesas Não operacionais')], max_length=255)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Passiva', 'Economia Passiva'), ('Agressiva', 'Economia Agressiva')], max_length=10)),
                ('porcentagem_despesa_fixa', models.FloatField()),
                ('porcentagem_despesa_variavel', models.FloatField()),
                ('porcentagem_despesa_geral', models.FloatField()),
                ('porcentagem_investimento', models.FloatField()),
                ('ajuste_automatico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('prazo', models.DateField()),
                ('frequencia', models.FloatField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primeiro_app.pessoa')),
            ],
        ),
    ]
