# Generated by Django 5.1.2 on 2024-12-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0003_despesa_perfileconomia_investimentos'),
        ('primeiro_app', '0003_meta'),
    ]

    operations = [
    ]
